/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include <MPU6050/Inc/MPU6050.h>
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxI2c_I2c.h"

static void i2c_init(void);
static void i2c_Device_init(void);

IfxCpu_syncEvent g_cpuSyncEvent = 0;

IfxI2c_I2c I2C_Handler;
IfxI2c_I2c_Config I2C_ConfigHandler;
IfxI2c_I2c_Device MPU6050_I2C;
IfxI2c_I2c_deviceConfig MPU6050_I2C_Config;
MPU6050_Typedef MPU6050;


int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    i2c_init();
    i2c_Device_init();

    MPU6050_Init(&MPU6050_I2C, &MPU6050, MPU6050_Dispositivo_2, MPU6050_Acelerometro_4g, MPU6050_Giroscopio_250);

    while(1)
    {
        MPU6050_LeerTodo(&MPU6050_I2C, &MPU6050);
    }
    return (1);
}

static void i2c_init(void)
{
    IfxI2c_I2c_initConfig(&I2C_ConfigHandler, &MODULE_I2C0);

    static IfxI2c_Pins Pines = {
            &IfxI2c0_SCL_P02_5_INOUT,
            &IfxI2c0_SDA_P02_4_INOUT,
            IfxPort_PadDriver_cmosAutomotiveSpeed1
    };

    I2C_ConfigHandler.pins = &Pines;
    I2C_ConfigHandler.baudrate = MPU6050_BAUDRATE;

    IfxI2c_I2c_initModule(&I2C_Handler, &I2C_ConfigHandler);
}

static void i2c_Device_init(void)
{
    IfxI2c_I2c_initDeviceConfig(&MPU6050_I2C_Config, &I2C_Handler);

    MPU6050_I2C.deviceAddress = MPU_I2C_DIR;

    IfxI2c_I2c_initDevice(&MPU6050_I2C, &MPU6050_I2C_Config);
}
